#!/usr/bin/env python3

import os
os.environ["TQDM_DISABLE"] = "1"
os.environ["QT_LOGGING_RULES"] = "*=false"
import argparse
import cv2
import zmq
import numpy as np
import re
import os
import torch
import sys
import textwrap

# Ensure to load local gripper networking file
try:
    from stretch4_gripper_modeling_and_control import gripper_networking as gn
    import visualization_utils as vu
except ImportError:
    pass # Assume gripper_networking is correctly provided in environment

import shared_arguments

from stretch4_gripper_modeling_and_control import telemetry_utils as tu
from stretch4_gripper_modeling_and_control.fingertip_visualizer import FingertipVisualizer
from stretch4_gripper_modeling_and_control.visualization_utils import draw_predicted_frames
from stretch4_gripper_modeling_and_control import aruco_to_fingertips as af

def extract_points(text, width, height):
    """
    Parses XML-like <point> format generated by Molmo to extract image coordinates
    Returns a list of tuples: [(x1, y1), (x2, y2), ...]
    """
    points = []
    
    # 1. Molmo 2 format: <points coords="1 1 418 735 2 546 735">
    for match in re.finditer(r'<points?[^>]*coords="([0-9\s]+)"', text):
        coords_str = match.group(1)
        coords = [int(v) for v in coords_str.split()]
        
        if len(coords) % 3 == 1 and len(coords) >= 4:
            coords = coords[1:] 
            
        if len(coords) % 3 == 0:
            for i in range(0, len(coords), 3):
                norm_x = coords[i+1] / 1000.0
                norm_y = coords[i+2] / 1000.0
                pixel_x = int(norm_x * width)
                pixel_y = int(norm_y * height)
                points.append((pixel_x, pixel_y))
                
        elif len(coords) > 0 and len(coords) % 2 == 0:
            for i in range(0, len(coords), 2):
                norm_x = coords[i] / 1000.0
                norm_y = coords[i+1] / 1000.0
                pixel_x = int(norm_x * width)
                pixel_y = int(norm_y * height)
                points.append((pixel_x, pixel_y))

    # 2. Older fallback Molmo format: <point x="0.123" y="0.456">
    pattern = r'<point.*?x="([0-9.]+)".*?y="([0-9.]+)".*?>'
    for match in re.finditer(pattern, text):
        norm_x = float(match.group(1))
        norm_y = float(match.group(2))
        
        if norm_x > 1.0 or norm_y > 1.0:
            norm_x = norm_x / 100.0
            norm_y = norm_y / 100.0
            
        pixel_x = int(norm_x * width)
        pixel_y = int(norm_y * height)
        points.append((pixel_x, pixel_y))
        
    return points

def load_molmo_model():
    print("Loading Molmo 2 VLM... this may take a moment.")
    from transformers import AutoModelForImageTextToText, AutoProcessor
    
    model_id = "allenai/Molmo2-8B" 
    
    try:
        processor = AutoProcessor.from_pretrained(
            model_id,
            trust_remote_code=True,
            torch_dtype=torch.bfloat16,
            device_map='auto'
        )
        model = AutoModelForImageTextToText.from_pretrained(
            model_id,
            trust_remote_code=True,
            torch_dtype=torch.bfloat16,
            device_map='auto'
        )
        return processor, model
    except Exception as e:
        print(f"Initial load failed (possibly network issue): {e}")
        print("Retrying with local_files_only=True...")
        try:
            processor = AutoProcessor.from_pretrained(
                model_id,
                trust_remote_code=True,
                torch_dtype=torch.bfloat16,
                device_map='auto',
                local_files_only=True
            )
            model = AutoModelForImageTextToText.from_pretrained(
                model_id,
                trust_remote_code=True,
                torch_dtype=torch.bfloat16,
                device_map='auto',
                local_files_only=True
            )
            return processor, model
        except Exception as e2:
            print(f"Failed to load Molmo 2. Make sure you installed dependencies and downloaded the model.")
            print(f"Error: {e2}")
            return None, None

    try:
        model_cfg = "configs/sam2.1/sam2.1_hiera_l.yaml"
        sam2 = build_sam2(model_cfg, weights_path, device='cuda', apply_postprocessing=False)
        return sam2
    except Exception as e:
        print(f"Failed to load SAM 2 model: {e}")
        return None

def overlay_mask(image, mask):
    """
    Overlays generated mask onto the image with a static color.
    """
    overlay = image.copy()
    color_mask = [255, 0, 0] # Blue mask
    
    mask_bool = mask.astype(bool).squeeze()
    overlay[mask_bool] = overlay[mask_bool] * 0.5 + np.array(color_mask) * 0.5
    return overlay

def create_text_visualization(image, text, object_description, point=None):
    """
    Creates a black region below the image, draws text using word wrapping, 
    and overlays the coordinate point.
    """
    H, W = image.shape[:2]
    # Increased panel height for more text space
    text_panel_h = 130
    panel = np.zeros((text_panel_h, W, 3), dtype=np.uint8)
    
    # Write the user's objective at the top of the panel in yellow, text in white
    text1 = "Object Description: "
    cv2.putText(panel, text1, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 255), 2)
    size_obj, _ = cv2.getTextSize(text1, cv2.FONT_HERSHEY_SIMPLEX, 0.8, 2)
    cv2.putText(panel, object_description, (10 + size_obj[0], 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2)
    
    text2 = "Molmo 2 Response: "
    cv2.putText(panel, text2, (10, 70), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 255), 2)
    size_molmo, _ = cv2.getTextSize(text2, cv2.FONT_HERSHEY_SIMPLEX, 0.8, 2)
    
    # Calculate word wrap width approximately based on font scale 0.7 (approx 12px per char)
    chars_per_line = max(40, int(W / 12))
    lines = textwrap.wrap(text2 + text, width=chars_per_line)
    
    y0, dy = 70, 25 # Start Molmo output lower down
    for i, line in enumerate(lines[:3]): # Support up to 3 rows
        if i == 0 and line.startswith(text2):
            val = line[len(text2):]
            cv2.putText(panel, val, (10 + size_molmo[0], y0), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
        else:
            cv2.putText(panel, line, (10, y0 + i*dy), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
        
    vis_img = image.copy()
    if point is not None:
        cv2.circle(vis_img, point, radius=10, color=(0, 255, 0), thickness=-1)
        cv2.circle(vis_img, point, radius=12, color=(0, 0, 255), thickness=2)
        
    return np.vstack((vis_img, panel))

def main():
    parser = argparse.ArgumentParser(
        prog='Receive Gripper Images with Molmo 2 and SAM 2 tracking',
        description='Receives gripper camera images, uses Molmo 2 to find an object, and SAM 2 to track it.'
    )
    shared_arguments.add_shared_arguments(parser)
    vu.add_display_scale_argument(parser)
    args = parser.parse_args()

    sub_context = zmq.Context()
    socket = sub_context.socket(zmq.SUB)
    socket.setsockopt(zmq.SUBSCRIBE, b'')
    socket.setsockopt(zmq.SNDHWM, 1)
    socket.setsockopt(zmq.RCVHWM, 1)
    socket.setsockopt(zmq.CONFLATE, 1)
    
    if args.remote:
        address = 'tcp://' + gn.robot_ip + ':' + str(gn.gripper_and_joints_port)
    else:
        address = 'tcp://127.0.0.1:' + str(gn.gripper_and_joints_port)
        
    print(f"Connecting ZMQ Subscriber to {address}")
    socket.connect(address)

    print("Waiting for first telemetry message to extract robot_id...")
    first_msg = socket.recv_pyobj()
    robot_id = first_msg.get('robot_id')
    if not robot_id:
        raise ValueError("The first telemetry message did not contain a 'robot_id'. Ensure send_gripper_images_and_joint_states.py is up to date.")
    print(f"Received robot_id '{robot_id}' from telemetry.")

    args = shared_arguments.resolve_model_path(args, robot_id)

    import sam2_utils as sam2
    # Load Models
    sam2_model, sam2_processor = sam2.load_sam2_model(args.sam2_model_id, args.tracking_mode)
    if sam2_model is None: return
    tracker = sam2.SAM2Tracker((sam2_model, sam2_processor), args.tracking_mode)

    molmo_proc, molmo_model = load_molmo_model()
    if not molmo_model or not molmo_proc:
        return

    print(f"Loading Fingertip Visualizer with model: {args.model}")
    visualizer = FingertipVisualizer(args.model)
    aruco_to_tips = af.ArucoToFingertips(
        default_height_above_mounting_surface=af.suctioncup_height['cup_top']
    )
        
    molmo_prompt = (
        f"<|image|> Point to {args.object_description} if it is visible in the image. "
        "If there are multiple objects, only point to the object that is closest. "
        "If there are multiple close objects, only point to the most centered object. "
        "Return ONLY the XML <points> coordinates for a single object or return ‘Object not found.’ "
        "Do not include any descriptive text."
    )

    reconstructor = tu.JointStateHistory(maxlen=400, warn_on_discontinuity=False) # about 4 seconds

    print("Receiving frames and joint states... Press 'q' or 'Esc' to quit.")
    
    tracking_mode = False
    last_mask = None
    molmo_display_image = None
    windows_resized = set()
    try:
        while True:
            output_dict = socket.recv_pyobj()
            
            if 'color_image_compressed' in output_dict:
                color_image = cv2.imdecode(np.frombuffer(output_dict['color_image_compressed'], np.uint8), cv2.IMREAD_COLOR)
            else:
                color_image = output_dict['color_image']
                
            joint_history = output_dict.get('joint_state_history', [])
            closest = output_dict.get('closest_joint_state', None)
            reconstructor.add_states(joint_history)

            rgb_camera_info = {
                'camera_matrix': output_dict.get('camera_matrix', np.eye(3)),
                'distortion_coefficients': output_dict.get('distortion_coefficients', np.zeros(5))
            }
            
            scaled_color_image, scaled_camera_info = vu.apply_display_scale(color_image, args.display_scale, camera_info=rgb_camera_info)
            display_image = scaled_color_image.copy()
            
            rgb_image = cv2.cvtColor(color_image, cv2.COLOR_BGR2RGB)
            H, W = rgb_image.shape[:2]

            if not tracking_mode:
                from PIL import Image
                pil_image = Image.fromarray(rgb_image)
                width, height = pil_image.size
                
                inputs = molmo_proc(
                    images=[pil_image],
                    text=molmo_prompt,
                    return_tensors="pt"
                )
                
                inputs = {k: v.to(molmo_model.device) for k, v in inputs.items()}
                if "pixel_values" in inputs:
                    inputs["pixel_values"] = inputs["pixel_values"].to(molmo_model.dtype)

                with torch.inference_mode():
                    output_ids = molmo_model.generate(
                        **inputs,
                        max_new_tokens=200,
                        stop_strings=["<|endoftext|>"],
                        tokenizer=molmo_proc.tokenizer
                    )
                
                generated_tokens = output_ids[0, inputs['input_ids'].size(1):]
                generated_text = molmo_proc.tokenizer.decode(generated_tokens, skip_special_tokens=True)
                
                print(f"Molmo response: {generated_text}")
                
                pt = None
                pt_scaled = None
                if "not found" not in generated_text.lower():
                    pts = extract_points(generated_text, width, height)
                    if len(pts) > 0:
                        pt = pts[0]
                        pt_scaled = (int(pt[0] * args.display_scale), int(pt[1] * args.display_scale))
                        print(f"Found point: {pt}. Initializing SAM 2 tracking...")
                        
                        last_mask = tracker.initialize_tracking(rgb_image, pt)
                        tracking_mode = True
                
                molmo_display_image = create_text_visualization(scaled_color_image, generated_text, args.object_description, point=pt_scaled)
            
            if tracking_mode:
                last_mask, target_lost = tracker.update_tracking(rgb_image)
                if target_lost:
                    print('SAM 2 target lost. Exiting...')
                    break

                if args.display_scale != 1.0:
                    scaled_mask = cv2.resize(last_mask.astype(np.uint8), (0, 0), fx=args.display_scale, fy=args.display_scale, interpolation=cv2.INTER_NEAREST)
                else:
                    scaled_mask = last_mask
                display_image = overlay_mask(scaled_color_image, scaled_mask)
            
            # Visualize kinematic model based on pos_pct
            if visualizer is not None and closest is not None:
                matched_pct = closest['gripper']['pos_pct']
                
                full_history_list = reconstructor.get_history_list()
                
                direction = 'closing'
                if len(full_history_list) > 10:
                    recent = full_history_list[-10:]
                    diff = recent[-1]['gripper']['pos_pct'] - recent[0]['gripper']['pos_pct']
                    direction = 'opening' if diff > 0 else 'closing'
                    
                predicted_fingertips = {}
                for side in ['left', 'right']:
                    pos_pred, rot_pred = visualizer.predict(side, matched_pct, direction)
                    if pos_pred is not None and rot_pred is not None:
                        predicted_fingertips[side] = {
                            'pos': pos_pred,
                            'x_axis': rot_pred[:, 0],
                            'y_axis': rot_pred[:, 1],
                            'z_axis': rot_pred[:, 2]
                        }
                        
                draw_predicted_frames(predicted_fingertips, display_image, scaled_camera_info)
                if aruco_to_tips is not None and not args.disable_suction_cups:
                    aruco_to_tips.draw_fingertip_suction_cups(predicted_fingertips, display_image, scaled_camera_info)

            if molmo_display_image is not None:
                h1, w1 = molmo_display_image.shape[:2]
                h2, w2 = display_image.shape[:2]
                
                if w1 != w2:
                    scale = w1 / float(w2)
                    display_image_scaled = cv2.resize(display_image, (int(w2 * scale), int(h2 * scale)))
                else:
                    display_image_scaled = display_image
                    
                combined_image = np.vstack((display_image_scaled, molmo_display_image))
                win_name = "Perception Pipeline"
                cv2.namedWindow(win_name, cv2.WINDOW_NORMAL)
                if win_name not in windows_resized:
                    cv2.resizeWindow(win_name, combined_image.shape[1], combined_image.shape[0])
                    windows_resized.add(win_name)
                cv2.imshow(win_name, combined_image)
            else:
                win_name = "Camera Stream"
                cv2.namedWindow(win_name, cv2.WINDOW_NORMAL)
                if win_name not in windows_resized:
                    cv2.resizeWindow(win_name, display_image.shape[1], display_image.shape[0])
                    windows_resized.add(win_name)
                cv2.imshow(win_name, display_image)
            
            key = cv2.waitKey(1) & 0xFF
            if key in (27, ord('q')):
                break
                
    except KeyboardInterrupt:
        pass
    finally:
        cv2.destroyAllWindows()
        print("\nStopped.")

if __name__ == '__main__':
    main()
