import re
import torch

def extract_points(text, width, height):
    """
    Parses XML-like <point> format generated by Molmo to extract image coordinates
    Returns a list of tuples: [(x1, y1), (x2, y2), ...]
    """
    points = []
    
    for match in re.finditer(r'<points?[^>]*coords="([0-9\s]+)"', text):
        coords_str = match.group(1)
        coords = [int(v) for v in coords_str.split()]
        
        if len(coords) % 3 == 1 and len(coords) >= 4:
            coords = coords[1:] 
            
        if len(coords) % 3 == 0:
            for i in range(0, len(coords), 3):
                norm_x = coords[i+1] / 1000.0
                norm_y = coords[i+2] / 1000.0
                pixel_x = int(norm_x * width)
                pixel_y = int(norm_y * height)
                points.append((pixel_x, pixel_y))
                
        elif len(coords) > 0 and len(coords) % 2 == 0:
            for i in range(0, len(coords), 2):
                norm_x = coords[i] / 1000.0
                norm_y = coords[i+1] / 1000.0
                pixel_x = int(norm_x * width)
                pixel_y = int(norm_y * height)
                points.append((pixel_x, pixel_y))

    pattern = r'<point.*?x="([0-9.]+)".*?y="([0-9.]+)".*?>'
    for match in re.finditer(pattern, text):
        norm_x = float(match.group(1))
        norm_y = float(match.group(2))
        
        if norm_x > 1.0 or norm_y > 1.0:
            norm_x = norm_x / 100.0
            norm_y = norm_y / 100.0
            
        pixel_x = int(norm_x * width)
        pixel_y = int(norm_y * height)
        points.append((pixel_x, pixel_y))
        
    return points

def load_molmo_model():
    print("Loading Molmo 2 VLM... this may take a moment.")
    from transformers import AutoModelForImageTextToText, AutoProcessor
    
    model_id = "allenai/Molmo2-8B" 
    
    # Mock transformers' internal offline mode to bypass DNS timeouts for local load
    try:
        import transformers.utils.hub
        original_offline_mode = transformers.utils.hub._is_offline_mode
        transformers.utils.hub._is_offline_mode = True
    except Exception:
        original_offline_mode = False
    
    try:
        processor = AutoProcessor.from_pretrained(
            model_id,
            trust_remote_code=True,
            torch_dtype=torch.bfloat16,
            device_map='auto',
            local_files_only=True
        )
        model = AutoModelForImageTextToText.from_pretrained(
            model_id,
            trust_remote_code=True,
            torch_dtype=torch.bfloat16,
            device_map='auto',
            local_files_only=True
        )
        # Restore original offline mode
        try:
            transformers.utils.hub._is_offline_mode = original_offline_mode
        except Exception:
            pass
            
        return processor, model
    except Exception as e:
        print(f"Local load failed (perhaps not downloaded yet): {e}")
        print("Retrying with Hugging Face download...")
        
        # Restore original offline mode to allow internet access
        try:
            transformers.utils.hub._is_offline_mode = original_offline_mode
        except Exception:
            pass
            
        try:
            processor = AutoProcessor.from_pretrained(
                model_id,
                trust_remote_code=True,
                torch_dtype=torch.bfloat16,
                device_map='auto'
            )
            model = AutoModelForImageTextToText.from_pretrained(
                model_id,
                trust_remote_code=True,
                torch_dtype=torch.bfloat16,
                device_map='auto'
            )
            return processor, model
        except Exception as e2:
            print(f"Failed to load Molmo 2. Make sure you installed dependencies and downloaded the model.")
            print(f"Error: {e2}")
            return None, None

def get_molmo_pointing_prompt(object_description):
    return (
        f"<|image|> Point to {object_description} if it is visible in the image. "
        "If there are multiple objects, only point to the object that is closest. "
        "If there are multiple close objects, only point to the most centered object. "
        "Return ONLY the XML <points> coordinates for a single object or return ‘Object not found.’ "
        "Do not include any descriptive text."
    )
